-- AnnaSuraksha Demo Seed Data
-- One INSERT IGNORE per row. Safe to re-run: existing rows are silently skipped.

INSERT IGNORE INTO beneficiaries (id, aadhaar_hash, masked_aadhaar, full_name, state_code, state_name, category, family_size, phone, rice_kg, wheat_kg, sugar_kg, kerosene_l, fps_shop_id, status, migrant, claim_state, claim_count, ghost_reason, ghost_layer, registered_at, last_claim_at, flagged_at, block_hash, prev_block_hash, block_height) VALUES (1, SHA2('987654321012',256), 'XXXX-XXXX-1012', 'Ramesh Kumar Singh', 'UP', 'Uttar Pradesh', 'BPL', 5, '9876543210', 25, 20, 1, 0, NULL, 'ACTIVE', 0, 'UP', 0, NULL, NULL, NOW(), NULL, NULL, NULL, NULL, NULL);
INSERT IGNORE INTO beneficiaries (id, aadhaar_hash, masked_aadhaar, full_name, state_code, state_name, category, family_size, phone, rice_kg, wheat_kg, sugar_kg, kerosene_l, fps_shop_id, status, migrant, claim_state, claim_count, ghost_reason, ghost_layer, registered_at, last_claim_at, flagged_at, block_hash, prev_block_hash, block_height) VALUES (2, SHA2('876543210923',256), 'XXXX-XXXX-0923', 'Meena Devi Yadav', 'UP', 'Uttar Pradesh', 'AAY', 6, '9765432109', 35, 25, 2, 1, NULL, 'ACTIVE', 0, 'UP', 0, NULL, NULL, NOW(), NULL, NULL, NULL, NULL, NULL);
INSERT IGNORE INTO beneficiaries (id, aadhaar_hash, masked_aadhaar, full_name, state_code, state_name, category, family_size, phone, rice_kg, wheat_kg, sugar_kg, kerosene_l, fps_shop_id, status, migrant, claim_state, claim_count, ghost_reason, ghost_layer, registered_at, last_claim_at, flagged_at, block_hash, prev_block_hash, block_height) VALUES (3, SHA2('765432109834',256), 'XXXX-XXXX-9834', 'Suresh Patil', 'MH', 'Maharashtra', 'PHH', 3, '9654321098', 15, 12, 1, 0, NULL, 'ACTIVE', 0, 'MH', 0, NULL, NULL, NOW(), NULL, NULL, NULL, NULL, NULL);
INSERT IGNORE INTO beneficiaries (id, aadhaar_hash, masked_aadhaar, full_name, state_code, state_name, category, family_size, phone, rice_kg, wheat_kg, sugar_kg, kerosene_l, fps_shop_id, status, migrant, claim_state, claim_count, ghost_reason, ghost_layer, registered_at, last_claim_at, flagged_at, block_hash, prev_block_hash, block_height) VALUES (4, SHA2('654321098745',256), 'XXXX-XXXX-8745', 'Lakshmi Bai Sharma', 'MP', 'Madhya Pradesh', 'BPL', 4, '9543210987', 20, 15, 1, 1, NULL, 'ACTIVE', 0, 'MP', 0, NULL, NULL, NOW(), NULL, NULL, NULL, NULL, NULL);
INSERT IGNORE INTO beneficiaries (id, aadhaar_hash, masked_aadhaar, full_name, state_code, state_name, category, family_size, phone, rice_kg, wheat_kg, sugar_kg, kerosene_l, fps_shop_id, status, migrant, claim_state, claim_count, ghost_reason, ghost_layer, registered_at, last_claim_at, flagged_at, block_hash, prev_block_hash, block_height) VALUES (5, SHA2('543210987656',256), 'XXXX-XXXX-7656', 'Arjun Das', 'WB', 'West Bengal', 'BPL', 2, '9432109876', 10, 10, 0, 0, NULL, 'ACTIVE', 0, 'WB', 0, NULL, NULL, NOW(), NULL, NULL, NULL, NULL, NULL);
INSERT IGNORE INTO beneficiaries (id, aadhaar_hash, masked_aadhaar, full_name, state_code, state_name, category, family_size, phone, rice_kg, wheat_kg, sugar_kg, kerosene_l, fps_shop_id, status, migrant, claim_state, claim_count, ghost_reason, ghost_layer, registered_at, last_claim_at, flagged_at, block_hash, prev_block_hash, block_height) VALUES (6, SHA2('432109876567',256), 'XXXX-XXXX-6567', 'Fatima Begum', 'RJ', 'Rajasthan', 'AAY', 8, '9321098765', 40, 30, 3, 2, NULL, 'ACTIVE', 0, 'RJ', 0, NULL, NULL, NOW(), NULL, NULL, NULL, NULL, NULL);
INSERT IGNORE INTO beneficiaries (id, aadhaar_hash, masked_aadhaar, full_name, state_code, state_name, category, family_size, phone, rice_kg, wheat_kg, sugar_kg, kerosene_l, fps_shop_id, status, migrant, claim_state, claim_count, ghost_reason, ghost_layer, registered_at, last_claim_at, flagged_at, block_hash, prev_block_hash, block_height) VALUES (7, SHA2('321098765478',256), 'XXXX-XXXX-5478', 'Venkatesh Reddy', 'AP', 'Andhra Pradesh', 'PHH', 3, '9210987654', 15, 12, 1, 0, NULL, 'ACTIVE', 0, 'AP', 0, NULL, NULL, NOW(), NULL, NULL, NULL, NULL, NULL);
INSERT IGNORE INTO beneficiaries (id, aadhaar_hash, masked_aadhaar, full_name, state_code, state_name, category, family_size, phone, rice_kg, wheat_kg, sugar_kg, kerosene_l, fps_shop_id, status, migrant, claim_state, claim_count, ghost_reason, ghost_layer, registered_at, last_claim_at, flagged_at, block_hash, prev_block_hash, block_height) VALUES (8, SHA2('210987654389',256), 'XXXX-XXXX-4389', 'Priya Nair', 'TN', 'Tamil Nadu', 'APL', 4, '9109876543', 0, 0, 0, 0, NULL, 'ACTIVE', 0, 'TN', 0, NULL, NULL, NOW(), NULL, NULL, NULL, NULL, NULL);
INSERT IGNORE INTO beneficiaries (id, aadhaar_hash, masked_aadhaar, full_name, state_code, state_name, category, family_size, phone, rice_kg, wheat_kg, sugar_kg, kerosene_l, fps_shop_id, status, migrant, claim_state, claim_count, ghost_reason, ghost_layer, registered_at, last_claim_at, flagged_at, block_hash, prev_block_hash, block_height) VALUES (9, SHA2('198765432210',256), 'XXXX-XXXX-2210', 'Rajiv Gupta', 'UP', 'Uttar Pradesh', 'BPL', 3, '9876012345', 15, 12, 1, 0, NULL, 'ACTIVE', 1, 'UP', 0, NULL, NULL, NOW(), NULL, NULL, NULL, NULL, NULL);
INSERT IGNORE INTO beneficiaries (id, aadhaar_hash, masked_aadhaar, full_name, state_code, state_name, category, family_size, phone, rice_kg, wheat_kg, sugar_kg, kerosene_l, fps_shop_id, status, migrant, claim_state, claim_count, ghost_reason, ghost_layer, registered_at, last_claim_at, flagged_at, block_hash, prev_block_hash, block_height) VALUES (10, SHA2('287654321121',256), 'XXXX-XXXX-1121', 'Anita Kumari', 'WB', 'West Bengal', 'PHH', 2, '9765101234', 10, 10, 0, 0, NULL, 'ACTIVE', 1, 'WB', 0, NULL, NULL, NOW(), NULL, NULL, NULL, NULL, NULL);
INSERT IGNORE INTO beneficiaries (id, aadhaar_hash, masked_aadhaar, full_name, state_code, state_name, category, family_size, phone, rice_kg, wheat_kg, sugar_kg, kerosene_l, fps_shop_id, status, migrant, claim_state, claim_count, ghost_reason, ghost_layer, registered_at, last_claim_at, flagged_at, block_hash, prev_block_hash, block_height) VALUES (11, SHA2('987654321012',256), 'XXXX-XXXX-1012', 'Ramesh K (Duplicate)', 'MH', 'Maharashtra', 'BPL', 5, NULL, 25, 20, 1, 0, NULL, 'GHOST', 0, 'MH', 0, 'Duplicate Aadhaar detected in MH (already registered in UP)', 'LAYER_1', NOW(), NULL, NOW(), NULL, NULL, NULL);
INSERT IGNORE INTO beneficiaries (id, aadhaar_hash, masked_aadhaar, full_name, state_code, state_name, category, family_size, phone, rice_kg, wheat_kg, sugar_kg, kerosene_l, fps_shop_id, status, migrant, claim_state, claim_count, ghost_reason, ghost_layer, registered_at, last_claim_at, flagged_at, block_hash, prev_block_hash, block_height) VALUES (12, SHA2('111222333444',256), 'XXXX-XXXX-3444', 'Unknown Single', 'GJ', 'Gujarat', 'AAY', 1, NULL, 35, 25, 2, 1, NULL, 'GHOST', 0, 'GJ', 0, 'AAY category requires a family single-person household is invalid', 'LAYER_2', NOW(), NULL, NOW(), NULL, NULL, NULL);
INSERT IGNORE INTO beneficiaries (id, aadhaar_hash, masked_aadhaar, full_name, state_code, state_name, category, family_size, phone, rice_kg, wheat_kg, sugar_kg, kerosene_l, fps_shop_id, status, migrant, claim_state, claim_count, ghost_reason, ghost_layer, registered_at, last_claim_at, flagged_at, block_hash, prev_block_hash, block_height) VALUES (13, SHA2('999888777666',256), 'XXXX-XXXX-7666', 'Speed Claimant', 'TN', 'Tamil Nadu', 'BPL', 4, '9000000001', 20, 15, 1, 0, NULL, 'GHOST', 1, 'MH', 0, 'Physically impossible cross-state claim: TN to MH in 3 hours', 'LAYER_3_VELOCITY', DATE_SUB(NOW(), INTERVAL 5 HOUR), DATE_SUB(NOW(), INTERVAL 2 HOUR), DATE_SUB(NOW(), INTERVAL 2 HOUR), NULL, NULL, NULL);

INSERT IGNORE INTO supply_chain_entries (id, stage, shipment_id, warehouse_id, fps_shop_id, state_code, district, dispatched_rice_kg, dispatched_wheat_kg, dispatched_sugar_kg, received_rice_kg, received_wheat_kg, received_sugar_kg, rice_discrepancy_kg, wheat_discrepancy_kg, sugar_discrepancy_kg, discrepancy_flagged, discrepancy_reason, warehouse_officer_id, transporter_id, fps_operator_id, entry_hash, prev_entry_hash, entry_height, dispatched_at, received_at, created_at) VALUES (1, 'RECEIVED', 'SHP-UP-0001', 'WH-UP-LUCKNOW-01', 'FPS-UP-0042', 'UP', 'UP-District', 500, 300, 50, 500, 300, 50, 0, 0, 0, 0, NULL, 'OFFICER-UP-001', 'TRANSPORTER-RAJ-01', 'FPS-OP-UP-42', NULL, NULL, 1, DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY));
INSERT IGNORE INTO supply_chain_entries (id, stage, shipment_id, warehouse_id, fps_shop_id, state_code, district, dispatched_rice_kg, dispatched_wheat_kg, dispatched_sugar_kg, received_rice_kg, received_wheat_kg, received_sugar_kg, rice_discrepancy_kg, wheat_discrepancy_kg, sugar_discrepancy_kg, discrepancy_flagged, discrepancy_reason, warehouse_officer_id, transporter_id, fps_operator_id, entry_hash, prev_entry_hash, entry_height, dispatched_at, received_at, created_at) VALUES (2, 'RECEIVED', 'SHP-MH-0002', 'WH-MH-MUMBAI-03', 'FPS-MH-1101', 'MH', 'MH-District', 800, 400, 60, 680, 390, 60, 120, 10, 0, 1, 'Rice shortage: 120 kg missing (15% above 5% threshold)', 'OFFICER-MH-007', 'TRANSPORTER-MH-99', 'FPS-OP-MH-1101', NULL, NULL, 2, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY));
INSERT IGNORE INTO supply_chain_entries (id, stage, shipment_id, warehouse_id, fps_shop_id, state_code, district, dispatched_rice_kg, dispatched_wheat_kg, dispatched_sugar_kg, received_rice_kg, received_wheat_kg, received_sugar_kg, rice_discrepancy_kg, wheat_discrepancy_kg, sugar_discrepancy_kg, discrepancy_flagged, discrepancy_reason, warehouse_officer_id, transporter_id, fps_operator_id, entry_hash, prev_entry_hash, entry_height, dispatched_at, received_at, created_at) VALUES (3, 'RECEIVED', 'SHP-WB-0003', 'WH-WB-KOLKATA-01', 'FPS-WB-0701', 'WB', 'WB-District', 350, 200, 30, 345, 198, 30, 5, 2, 0, 0, NULL, 'OFFICER-WB-003', 'TRANSPORTER-WB-11', 'FPS-OP-WB-701', NULL, NULL, 3, DATE_SUB(NOW(), INTERVAL 1 DAY), NOW(), DATE_SUB(NOW(), INTERVAL 1 DAY));

INSERT IGNORE INTO claim_records (id, beneficiary_id, beneficiary_name, aadhaar_hash, state_code, claim_state_code, fps_shop_id, category, rice_kg, wheat_kg, sugar_kg, tx_hash, block_height, biometric_status, claimed_at) VALUES (1, 1, 'Ramesh Kumar Singh', SHA2('987654321012',256), 'UP', 'UP', NULL, 'BPL', 25, 20, 1, NULL, 1, 'VERIFIED', DATE_SUB(NOW(), INTERVAL 5 DAY));
INSERT IGNORE INTO claim_records (id, beneficiary_id, beneficiary_name, aadhaar_hash, state_code, claim_state_code, fps_shop_id, category, rice_kg, wheat_kg, sugar_kg, tx_hash, block_height, biometric_status, claimed_at) VALUES (2, 2, 'Meena Devi Yadav', SHA2('876543210923',256), 'UP', 'UP', NULL, 'AAY', 35, 25, 2, NULL, 2, 'VERIFIED', DATE_SUB(NOW(), INTERVAL 4 DAY));
INSERT IGNORE INTO claim_records (id, beneficiary_id, beneficiary_name, aadhaar_hash, state_code, claim_state_code, fps_shop_id, category, rice_kg, wheat_kg, sugar_kg, tx_hash, block_height, biometric_status, claimed_at) VALUES (3, 3, 'Suresh Patil', SHA2('765432109834',256), 'MH', 'MH', NULL, 'PHH', 15, 12, 1, NULL, 3, 'VERIFIED', DATE_SUB(NOW(), INTERVAL 3 DAY));
INSERT IGNORE INTO claim_records (id, beneficiary_id, beneficiary_name, aadhaar_hash, state_code, claim_state_code, fps_shop_id, category, rice_kg, wheat_kg, sugar_kg, tx_hash, block_height, biometric_status, claimed_at) VALUES (4, 4, 'Lakshmi Bai Sharma', SHA2('654321098745',256), 'MP', 'MP', NULL, 'BPL', 20, 15, 1, NULL, 4, 'VERIFIED', DATE_SUB(NOW(), INTERVAL 2 DAY));
INSERT IGNORE INTO claim_records (id, beneficiary_id, beneficiary_name, aadhaar_hash, state_code, claim_state_code, fps_shop_id, category, rice_kg, wheat_kg, sugar_kg, tx_hash, block_height, biometric_status, claimed_at) VALUES (5, 5, 'Arjun Das', SHA2('543210987656',256), 'WB', 'WB', NULL, 'BPL', 10, 10, 0, NULL, 5, 'VERIFIED', DATE_SUB(NOW(), INTERVAL 1 DAY));
INSERT IGNORE INTO claim_records (id, beneficiary_id, beneficiary_name, aadhaar_hash, state_code, claim_state_code, fps_shop_id, category, rice_kg, wheat_kg, sugar_kg, tx_hash, block_height, biometric_status, claimed_at) VALUES (6, 6, 'Fatima Begum', SHA2('432109876567',256), 'RJ', 'RJ', NULL, 'AAY', 40, 30, 3, NULL, 6, 'VERIFIED', NOW());
